name: meal_app
description: A new Flutter project.


publish_to: 'none' 



version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  provider:
  cached_network_image: ^3.2.3
  shared_preferences: ^2.2.0
  flutter_colorpicker: ^1.0.3

  
  
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0

flutter:
  
  uses-material-design: true

  assets:
    - Images/a2.png
    - Images/image.jpg

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
